### ISSUE TITLE
Headless authentication

### ISSUE THREAD

**Issue by aloneguid** [OneNoteDev/OneNoteAPISampleWinUniversal#5]
Apologies if this is not the right repo to ask (I'm sure it's not). I'm trying to create a headless daemon that can post to OneNote pages. The API are looking great, however I can't find an example on how to authenticate from a console app before making any requests. 

My notebooks are both in O365 subs and some are in MSA accounts. I'd be grateful if you can point me to understanding either case as i'm totally stuck here.

**Comment by jogonzal** [comment]
Hey @aloneguid , no worries! We usually respond to these kind of questions in stackoverflow, so you can ask there (just tag it with onenote-api: https://stackoverflow.com/questions/tagged/onenote-api.

Auth with console agents is a bit special: I've done it before by creating an HttpListener and popping a browser window that eventually redirects to that HttpListener. We don't have a code sample for it, but this one is pretty much the same (only google auth instead of MS auth) https://github.com/googlesamples/oauth-apps-for-windows/tree/master/OAuthConsoleApp/OAuthConsoleApp.

Good luck!

**Comment by aloneguid** [comment]
Thanks @jogonzal I've finally figured this out by using ADAL v3 to obtain bearer token and using samples in this repo. OneNote is a genius product!
